workflows:
  flutter-ios-simulator:
        name: Flutter iOS Simulator
        environment:
          groups:
            - android
          flutter: 3.29.0
          xcode: 16.2
        scripts:
          - name: Check envs
            script: |
              echo "📦 Bundle Identifier atual: $PRODUCT_BUNDLE_IDENTIFIER"
              echo "📄 Provisioning Profile: $APPSTORE_MOBILEPROVISION"
              echo "🏷️ Build Number: $FLUTTER_BUILD_NUMBER"
              echo "🚀 Build Name: $FLUTTER_BUILD_NAME"
          - name: Restore GoogleService-Info.plist
            script: |
              echo "$GOOGLE_SERVICE_PLIST_B64" | base64 --decode > ios/Runner/GoogleService-Info.plist
          - script: flutter clean
          - name: Get Flutter packages
            script: |
              flutter pub get
          - name: Check GoogleService-Info.plist exists
            script: |
              if [ -f ios/Runner/GoogleService-Info.plist ]; then
                echo "✅ GoogleService-Info.plist restored!"
                ls -l ios/Runner/GoogleService-Info.plistN
              else
                echo "❌ GoogleService-Info.plist NOT found!"
                exit 1
              fi
          - name: Build for iOS Simulator
            script: |
              flutter build ios
        artifacts:
          - build/ios/iphonesimulator/Runner.app
        cache:
          cache_paths:
            - $FLUTTER_ROOT/.pub-cache
            - ios/Pods

app-store:
  name: Apple Workflow
  environment:
    groups:
      - ios
    ios_signing:
      distribution_type: app_store
      bundle_identifier: br.com.profair.profair
      certificates:
        - api_key_profair_renew

  scripts:
    - name: Restore provisioning profile
      script: |
        echo "🔄 Restaurando provisioning profile"
        rm -f ~/Library/MobileDevice/Provisioning\ Profiles/*
        echo "$APPSTORE_MOBILEPROVISION" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profair.mobileprovision
        security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/profair.mobileprovision > profile.plist
        UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" profile.plist)
        echo "✅ Provisioning Profile UUID: $UUID"
        echo $UUID > profile_uuid.txt

    - name: Check Runner.entitlements
      script: |
        cat ios/Runner/Runner.entitlements

    - name: Ensure CODE_SIGN_ENTITLEMENTS
      script: |
        echo "🔍 Garantindo CODE_SIGN_ENTITLEMENTS no .pbxproj"
        sed -i '' 's|CODE_SIGN_ENTITLEMENTS =.*|CODE_SIGN_ENTITLEMENTS = Runner/Runner.entitlements;|' ios/Runner.xcodeproj/project.pbxproj
        grep -A2 CODE_SIGN_ENTITLEMENTS ios/Runner.xcodeproj/project.pbxproj

    - name: Clean & prepare
      script: |
        cd ios
        pod install
        cd ..

    - name: Archive with xcodebuild
      script: |
        UUID=$(cat profile_uuid.txt)
        echo "📦 Arquivando projeto com xcodebuild"
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath build/Runner.xcarchive \
          clean archive \
          DEVELOPMENT_TEAM=B4DCW8V3J4 \
          PROVISIONING_PROFILE_SPECIFIER=$UUID \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="Apple Distribution" \
          PRODUCT_BUNDLE_IDENTIFIER=br.com.profair.profair \
          CODE_SIGN_ENTITLEMENTS=Runner/Runner.entitlements

    - name: Export .ipa
      script: |
        echo "📦 Exportando IPA com xcodebuild"
        cat > export_options.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>app-store</string>
          <key>signingStyle</key>
          <string>manual</string>
          <key>teamID</key>
          <string>B4DCW8V3J4</string>
          <key>provisioningProfiles</key>
          <dict>
            <key>br.com.profair.profair</key>
            <string>$UUID</string>
          </dict>
        </dict>
        </plist>
        EOF

        xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportPath build/ipa \
          -exportOptionsPlist export_options.plist

    - name: Verify aps-environment in .ipa
      script: |
        unzip -q build/ipa/*.ipa -d extracted
        codesign -d --entitlements :- extracted/Payload/*.app > built_entitlements.plist
        echo "🔍 aps-environment encontrado:"
        grep -A1 '<key>aps-environment</key>' built_entitlements.plist || echo "⚠️ NÃO encontrado!"

  artifacts:
    - build/ipa/*.ipa

  publishing:
    app_store_connect:
      auth: integration
      submit_to_app_store: true
      release_type: SCHEDULED
      copyright: 2025 Profair






  android:
    name: Android Workflow
    environment:
      flutter: 3.29.0
      android_signing:
        - profair_keystore_android
      groups:
        - android
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Set up key.properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> android/key.properties
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: production
