# org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
# org.gradle.jvmargs=-Xmx1536M
# android.useAndroidX=true
# android.enableJetifier=true
# dev.steenbakker.mobile_scanner.useUnbundled=true

org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
dev.steenbakker.mobile_scanner.useUnbundled=true