// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZzV9ZH_nGRhNOVjVx6W8eM-Yh-eEpHGY',
    appId: '1:252078218557:web:044ccc9ff8e682c743f954',
    messagingSenderId: '252078218557',
    projectId: 'appprofair',
    authDomain: 'appprofair.firebaseapp.com',
    storageBucket: 'appprofair.firebasestorage.app',
    measurementId: 'G-HQMBL3L3EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8ECpdohAXZfWMgf9DdSkJto-cbe4JMU',
    appId: '1:252078218557:android:69553b56689ed42e43f954',
    messagingSenderId: '252078218557',
    projectId: 'appprofair',
    storageBucket: 'appprofair.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlSh2DZRFqZ7_I1tAIPKDE19IgwZU8a0s',
    appId: '1:252078218557:ios:fbf3dc3c9b5aad6c43f954',
    messagingSenderId: '252078218557',
    projectId: 'appprofair',
    storageBucket: 'appprofair.firebasestorage.app',
    iosBundleId: 'br.com.profair.profair',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlSh2DZRFqZ7_I1tAIPKDE19IgwZU8a0s',
    appId: '1:252078218557:ios:fbf3dc3c9b5aad6c43f954',
    messagingSenderId: '252078218557',
    projectId: 'appprofair',
    storageBucket: 'appprofair.firebasestorage.app',
    iosBundleId: 'br.com.profair.profair',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZzV9ZH_nGRhNOVjVx6W8eM-Yh-eEpHGY',
    appId: '1:252078218557:web:27edb04765e1828443f954',
    messagingSenderId: '252078218557',
    projectId: 'appprofair',
    authDomain: 'appprofair.firebaseapp.com',
    storageBucket: 'appprofair.firebasestorage.app',
    measurementId: 'G-L0QFZT968C',
  );
}
